<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CopilotBuddy.Core\CopilotBuddy.Core.csproj"
                      AdditionalProperties="CopilotBuddyRuntimeIdentifier=$(RuntimeIdentifier)" />
    <ProjectReference Include="..\CopilotBuddy.Copilot\CopilotBuddy.Copilot.csproj"
                      AdditionalProperties="CopilotBuddyRuntimeIdentifier=$(RuntimeIdentifier)" />
    <Content Include="Assets\Sprites\**\*.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Fonts\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="presentation.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>